# TODO: vi-mode char like starship
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_DIR_TRUNC_PREFIX="…/"
SPACESHIP_ASYNC_SHOW=false
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_SYMBOL="✘ "

SPACESHIP_JAVA_SYMBOL=" "
SPACESHIP_JAVA_COLOR="red"
SPACESHIP_GCLOUD_SHOW=false
